.PHONY: deps sponsors compile test

default: deps sponsors compile test

deps:
	scripts/dep.sh Olical aniseed origin/develop
	scripts/dep.sh Olical bencode origin/master

sponsors:
	echo "[ ;; Generated by: make sponsors" > fnl/conjure/sponsors.fnl
	curl https://github.com/sponsors/Olical \
		| grep '"avatar avatar-user"' \
		| sed 's/.*alt="@\(.*\)".*/"\1"/' \
		| tail -n +2 \
		| sort \
		>> fnl/conjure/sponsors.fnl
	echo "]" >> fnl/conjure/sponsors.fnl

compile:
	rm -rf lua
	deps/aniseed/scripts/embed.sh aniseed conjure
	ANISEED_EMBED_PREFIX=conjure deps/aniseed/scripts/compile.sh
	cp deps/bencode/bencode.lua lua/conjure/remote/transport/bencode/impl.lua

test:
	rm -rf test/lua
	deps/aniseed/scripts/test.sh
