.PHONY: deps sponsors test

default: deps sponsors test

deps:
	scripts/dep.sh Olical bencode origin/master

sponsors:
	echo "[ ;; Generated by: make sponsors" > fnl/conjure/sponsors.fnl
	curl https://github.com/sponsors/Olical \
		| grep '"avatar avatar-user"' \
		| sed 's/.*alt="@\(.*\)".*/"\1"/' \
		| tail -n +2 \
		| sort \
		>> fnl/conjure/sponsors.fnl
	echo "]" >> fnl/conjure/sponsors.fnl

test:
	./scripts/setup-test-deps
	./scripts/test
