[tasks.deps]
run = "scripts/dep.sh Olical bencode origin/master"

[tasks.sponsors]
run = "scripts/sponsors.sh"

[tasks.test]
# tools.neovim = "0.9.5"
run = ["scripts/setup-test-deps", "scripts/test"]
