= Conjure

== Conversational software development for https://neovim.io[Neovim]

Conjure is an interactive environment for evaluating code and inspecting your program.

_insert demo gif here_

The core features of Conjure are language agnostic (although it's targeted at Lisps for now), with each language module providing their own extra tools. Here's the language support so far, unchecked items are planned for the future.

 * [x] https://fennel-lang.org/[Fennel] inside Neovim via Lua and https://github.com/Olical/aniseed[Aniseed] (which Conjure is written in)
 * [x] https://clojure.org/[Clojure] over https://nrepl.org/[nREPL]
 * [ ] https://clojure.org/[Clojure] over https://oli.me.uk/clojure-socket-prepl-cookbook/[prepl]
 * [ ] https://janet-lang.org/[Janet]
 * [ ] https://racket-lang.org/[Racket]
 * [ ] Scheme (Chicken, Chez or Guile? All?)

== Installation

Use your favourite plugin manager, mine is https://github.com/junegunn/vim-plug[vim-plug] but any will do. Be sure to pin it to a tag and subscribe to releases through GitHub to avoid any surprises in the future.

[source,viml]
----
Plug 'Olical/conjure', {'tag': 'v3.0.0'}
----

You'll need to be on the latest stable Neovim for all of the features (such as floating windows) to work. If you see errors, please check what version you have against the latest stable release first.

== Getting started

All further documentation is found within Neovim itself, so hop into Neovim with Conjure installed and execute `:help conjure` to begin your journey.

== Behind the curtain

Conjure is written entirely in Lua (no VimL or external processes!) which is compiled from https://fennel-lang.org/[Fennel] by https://github.com/Olical/aniseed[Aniseed] ahead of time. Check out `CONTRIBUTING.adoc` for more on how to work on Conjure using itself, contributions are more than welcome!

Historically Conjure has been a Clojure specific plugin with an entirely different implementation, you can still find that version at https://github.com/Olical/conjure/tree/v2.1.2[v2.1.2].

== Unlicenced

Find the full http://unlicense.org/[unlicense] in the `UNLICENSE` file, but here's a snippet.

____
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.
____
