#!/usr/bin/env bash

echo "[ ;; Generated by: scripts/sponsors.sh" >fnl/conjure/sponsors.fnl
curl https://github.com/sponsors/Olical |
  grep '"avatar avatar-user"' |
  sed 's/.*alt="@\(.*\)".*/"\1"/' |
  tail -n +2 |
  sort \
    >>fnl/conjure/sponsors.fnl
echo "]" >>fnl/conjure/sponsors.fnl
nvim fnl/conjure/sponsors.fnl +wq
