name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim-version: ["v0.9.5", "v0.10.4", "stable", "nightly"]

    steps:
      - uses: actions/checkout@v4
      - name: Install Mise
        uses: jdx/mise-action@v2
      - name: Test
        run: |
          mise run -t neovim@${{ matrix.neovim-version }} test
